name: Build and Push Docker Image

on:
  push:
      branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build Docker Image
              run: docker build -t harisshakeel161/flight-tracker:latest .

            - name: Push Docker Image
              run: docker push harisshakeel161/flight-tracker:latest

            - name: Deploy to EC2
              run: |
                    echo "${{ secrets.EC2_SSH_KEY }}" > private_key.pem
                    chmod 600 private_key.pem
                    ssh -o StrictHostKeyChecking=no -i private_key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
                      docker pull harisshakeel161/flight-tracker:latest
                      docker stop flight-tracker-app || true
                      docker rm flight-tracker-app || true
                      docker run -d -p 3000:3000 --name flight-tracker-app harisshakeel161/flight-tracker:latest
                    EOF
                        